import type { Tenant } from "@/types";

/**
 * Único origen de datos del comercio. Cambiar este archivo cambia el comercio
 * entero: nombres, categorías, árbol, marcas y productos.
 */
export const seedTenant: Tenant = {
  name: "Despensa Vallejos",
  logoUrl: "",
  facadeImageUrl: "",
  rating: 4.7,
  isOpen: true,
  paymentMethods: ["Efectivo", "Débito", "Crédito", "QR", "Transferencia"],
  offerProductIds: ["p-atun-1", "p-arroz-1", "p-lavandina-1", "p-malbec-1", "p-yogur-1"],
  brands: [
    { id: "b-marolio", name: "Marolio", logoUrl: "" },
    { id: "b-lacampagnola", name: "La Campagnola", logoUrl: "" },
    { id: "b-arcor", name: "Arcor", logoUrl: "" },
    { id: "b-molinos", name: "Molinos", logoUrl: "" },
    { id: "b-ayudin", name: "Ayudín", logoUrl: "" },
    { id: "b-serenisima", name: "La Serenísima", logoUrl: "" },
    { id: "b-trapiche", name: "Trapiche", logoUrl: "" },
    { id: "b-dove", name: "Dove", logoUrl: "" },
  ],
  categories: [
    {
      id: "c-almacen",
      name: "Almacén",
      thumbnailProductIds: ["p-arroz-1", "p-fideos-1", "p-atun-1", "p-aceite-1"],
      children: [
        {
          id: "c-secos",
          name: "Alimentos secos",
          thumbnailProductIds: ["p-arroz-1", "p-fideos-1", "p-harina-1"],
          brandIds: ["b-molinos", "b-marolio", "b-arcor"],
        },
        {
          id: "c-enlatados",
          name: "Enlatados y conservas",
          thumbnailProductIds: ["p-atun-1", "p-duraznos-1", "p-picadillo-1", "p-lentejas-1"],
          children: [
            {
              id: "c-pescados",
              name: "Pescados enlatados",
              thumbnailProductIds: ["p-atun-1", "p-caballa-1", "p-sardinas-1"],
              brandIds: ["b-marolio", "b-lacampagnola"],
            },
            {
              id: "c-frutasyverduras",
              name: "Frutas y verduras enlatadas",
              thumbnailProductIds: ["p-duraznos-1", "p-ensalada-1", "p-jardinera-1", "p-cocktail-1"],
              children: [
                {
                  id: "c-frutas",
                  name: "Frutas",
                  thumbnailProductIds: ["p-duraznos-1", "p-ananas-1"],
                  brandIds: ["b-lacampagnola", "b-arcor"],
                },
                {
                  id: "c-ensaladas",
                  name: "Ensaladas",
                  thumbnailProductIds: ["p-ensalada-1"],
                  brandIds: ["b-lacampagnola"],
                },
                {
                  id: "c-jardineras",
                  name: "Jardineras",
                  thumbnailProductIds: ["p-jardinera-1"],
                  brandIds: ["b-marolio"],
                },
                {
                  id: "c-cocktails",
                  name: "Cocktails",
                  thumbnailProductIds: ["p-cocktail-1"],
                  brandIds: ["b-arcor"],
                },
              ],
            },
            {
              id: "c-picadillos",
              name: "Picadillos",
              thumbnailProductIds: ["p-picadillo-1"],
              brandIds: ["b-marolio"],
            },
            {
              id: "c-legumbres",
              name: "Legumbres",
              thumbnailProductIds: ["p-lentejas-1", "p-garbanzos-1"],
              brandIds: ["b-lacampagnola", "b-marolio"],
            },
          ],
        },
        {
          id: "c-aceites",
          name: "Aceites salsas y condimentos",
          thumbnailProductIds: ["p-aceite-1", "p-pure-1", "p-oregano-1"],
          brandIds: ["b-marolio", "b-lacampagnola"],
        },
        {
          id: "c-panificados",
          name: "Panificados y crackers",
          thumbnailProductIds: ["p-crackers-1", "p-tostadas-1"],
          brandIds: ["b-arcor", "b-molinos"],
        },
      ],
    },
    {
      id: "c-limpieza",
      name: "Limpieza",
      thumbnailProductIds: ["p-lavandina-1", "p-detergente-1", "p-jabonpolvo-1"],
      children: [
        {
          id: "c-lavado",
          name: "Lavado de ropa",
          thumbnailProductIds: ["p-jabonpolvo-1"],
          brandIds: ["b-ayudin"],
        },
        {
          id: "c-cocina-limpieza",
          name: "Cocina",
          thumbnailProductIds: ["p-detergente-1"],
          brandIds: ["b-ayudin", "b-marolio"],
        },
        {
          id: "c-desinfectantes",
          name: "Desinfectantes",
          thumbnailProductIds: ["p-lavandina-1"],
          brandIds: ["b-ayudin"],
        },
      ],
    },
    {
      id: "c-vinos",
      name: "Vinos",
      thumbnailProductIds: ["p-malbec-1", "p-cabernet-1"],
      children: [
        {
          id: "c-tintos",
          name: "Tintos",
          thumbnailProductIds: ["p-malbec-1", "p-cabernet-1"],
          brandIds: ["b-trapiche"],
        },
        {
          id: "c-blancos",
          name: "Blancos",
          thumbnailProductIds: ["p-chardonnay-1"],
          brandIds: ["b-trapiche"],
        },
      ],
    },
    {
      id: "c-lacteos",
      name: "Lácteos",
      thumbnailProductIds: ["p-leche-1", "p-yogur-1", "p-queso-1"],
      children: [
        {
          id: "c-leches",
          name: "Leches",
          thumbnailProductIds: ["p-leche-1"],
          brandIds: ["b-serenisima"],
        },
        {
          id: "c-yogures",
          name: "Yogures",
          thumbnailProductIds: ["p-yogur-1"],
          brandIds: ["b-serenisima"],
        },
        {
          id: "c-quesos",
          name: "Quesos",
          thumbnailProductIds: ["p-queso-1"],
          brandIds: ["b-serenisima"],
        },
      ],
    },
    {
      id: "c-carnes",
      name: "Carnes",
      thumbnailProductIds: ["p-asado-1", "p-pollo-1"],
      children: [
        {
          id: "c-vacuna",
          name: "Vacuna",
          thumbnailProductIds: ["p-asado-1"],
          brandIds: ["b-molinos"],
        },
        {
          id: "c-aves",
          name: "Aves",
          thumbnailProductIds: ["p-pollo-1"],
          brandIds: ["b-molinos"],
        },
      ],
    },
    {
      id: "c-perfumeria",
      name: "Perfumería",
      thumbnailProductIds: ["p-shampoo-1", "p-jabontocador-1"],
      children: [
        {
          id: "c-cabello",
          name: "Cabello",
          thumbnailProductIds: ["p-shampoo-1"],
          brandIds: ["b-dove"],
        },
        {
          id: "c-cuerpo",
          name: "Cuerpo",
          thumbnailProductIds: ["p-jabontocador-1"],
          brandIds: ["b-dove"],
        },
      ],
    },
  ],
  stackedCategories: [
    { id: "c-kiosco", name: "Kiosco", brandIds: ["b-arcor"], thumbnailProductIds: ["p-alfajor-1"] },
    { id: "c-bazar", name: "Bazar", brandIds: ["b-marolio"], thumbnailProductIds: [] },
    { id: "c-juguetes", name: "Juguetes", brandIds: [], thumbnailProductIds: [] },
    { id: "c-ropa", name: "Ropa", brandIds: [], thumbnailProductIds: [] },
  ],
  products: [
    {
      id: "p-arroz-1",
      name: "Arroz largo fino",
      brandId: "b-molinos",
      categoryId: "c-secos",
      color: "oklch(0.82 0.06 95)",
      variants: [
        { label: "500 gr", price: 1200 },
        { label: "1 kg", price: 2150 },
      ],
      inStock: true,
    },
    {
      id: "p-fideos-1",
      name: "Fideos tirabuzón",
      brandId: "b-marolio",
      categoryId: "c-secos",
      color: "oklch(0.78 0.09 80)",
      variants: [{ label: "500 gr", price: 990 }],
      inStock: true,
    },
    {
      id: "p-harina-1",
      name: "Harina 000",
      brandId: "b-molinos",
      categoryId: "c-secos",
      color: "oklch(0.88 0.02 90)",
      variants: [
        { label: "1 kg", price: 1050 },
        { label: "5 kg", price: 4800 },
      ],
      inStock: false,
    },
    {
      id: "p-atun-1",
      name: "Atún al natural",
      brandId: "b-lacampagnola",
      categoryId: "c-pescados",
      color: "oklch(0.7 0.11 235)",
      variants: [
        { label: "170 gr", price: 2400 },
        { label: "Pack x3", price: 6600 },
      ],
      inStock: true,
    },
    {
      id: "p-caballa-1",
      name: "Caballa en aceite",
      brandId: "b-marolio",
      categoryId: "c-pescados",
      color: "oklch(0.6 0.09 250)",
      variants: [{ label: "380 gr", price: 2900 }],
      inStock: true,
    },
    {
      id: "p-sardinas-1",
      name: "Sardinas en tomate",
      brandId: "b-marolio",
      categoryId: "c-pescados",
      color: "oklch(0.58 0.13 30)",
      variants: [{ label: "125 gr", price: 1700 }],
      inStock: false,
    },
    {
      id: "p-duraznos-1",
      name: "Duraznos en almíbar",
      brandId: "b-lacampagnola",
      categoryId: "c-frutas",
      color: "oklch(0.82 0.13 70)",
      variants: [
        { label: "820 gr", price: 3100 },
        { label: "480 gr", price: 1950 },
      ],
      inStock: true,
    },
    {
      id: "p-ananas-1",
      name: "Ananá en rodajas",
      brandId: "b-arcor",
      categoryId: "c-frutas",
      color: "oklch(0.86 0.14 95)",
      variants: [{ label: "820 gr", price: 3450 }],
      inStock: true,
    },
    {
      id: "p-ensalada-1",
      name: "Ensalada de frutas",
      brandId: "b-lacampagnola",
      categoryId: "c-ensaladas",
      color: "oklch(0.8 0.1 40)",
      variants: [{ label: "820 gr", price: 3300 }],
      inStock: true,
    },
    {
      id: "p-jardinera-1",
      name: "Jardinera de verduras",
      brandId: "b-marolio",
      categoryId: "c-jardineras",
      color: "oklch(0.72 0.12 145)",
      variants: [{ label: "350 gr", price: 1600 }],
      inStock: true,
    },
    {
      id: "p-cocktail-1",
      name: "Cocktail de frutas",
      brandId: "b-arcor",
      categoryId: "c-cocktails",
      color: "oklch(0.84 0.11 55)",
      variants: [{ label: "820 gr", price: 3500 }],
      inStock: true,
    },
    {
      id: "p-picadillo-1",
      name: "Picadillo de carne",
      brandId: "b-marolio",
      categoryId: "c-picadillos",
      color: "oklch(0.55 0.12 25)",
      variants: [{ label: "90 gr", price: 850 }],
      inStock: true,
    },
    {
      id: "p-lentejas-1",
      name: "Lentejas remojadas",
      brandId: "b-lacampagnola",
      categoryId: "c-legumbres",
      color: "oklch(0.5 0.07 60)",
      variants: [{ label: "350 gr", price: 1450 }],
      inStock: true,
    },
    {
      id: "p-garbanzos-1",
      name: "Garbanzos",
      brandId: "b-marolio",
      categoryId: "c-legumbres",
      color: "oklch(0.75 0.07 85)",
      variants: [{ label: "350 gr", price: 1500 }],
      inStock: true,
    },
    {
      id: "p-aceite-1",
      name: "Aceite de girasol",
      brandId: "b-marolio",
      categoryId: "c-aceites",
      color: "oklch(0.85 0.13 100)",
      variants: [
        { label: "900 ml", price: 2600 },
        { label: "1,5 lt", price: 4100 },
      ],
      inStock: true,
    },
    {
      id: "p-pure-1",
      name: "Puré de tomate",
      brandId: "b-lacampagnola",
      categoryId: "c-aceites",
      color: "oklch(0.55 0.17 28)",
      variants: [{ label: "520 gr", price: 980 }],
      inStock: true,
    },
    {
      id: "p-oregano-1",
      name: "Orégano",
      brandId: "b-marolio",
      categoryId: "c-aceites",
      color: "oklch(0.62 0.1 140)",
      variants: [{ label: "25 gr", price: 700 }],
      inStock: true,
    },
    {
      id: "p-crackers-1",
      name: "Crackers clásicas",
      brandId: "b-arcor",
      categoryId: "c-panificados",
      color: "oklch(0.8 0.08 75)",
      variants: [{ label: "300 gr", price: 1350 }],
      inStock: true,
    },
    {
      id: "p-tostadas-1",
      name: "Tostadas de salvado",
      brandId: "b-molinos",
      categoryId: "c-panificados",
      color: "oklch(0.68 0.06 70)",
      variants: [{ label: "200 gr", price: 1600 }],
      inStock: true,
    },
    {
      id: "p-lavandina-1",
      name: "Lavandina en gel",
      brandId: "b-ayudin",
      categoryId: "c-desinfectantes",
      color: "oklch(0.72 0.11 210)",
      variants: [
        { label: "1 lt", price: 1800 },
        { label: "2 lt", price: 3100 },
      ],
      inStock: true,
    },
    {
      id: "p-detergente-1",
      name: "Detergente concentrado",
      brandId: "b-ayudin",
      categoryId: "c-cocina-limpieza",
      color: "oklch(0.75 0.13 150)",
      variants: [{ label: "750 ml", price: 2200 }],
      inStock: true,
    },
    {
      id: "p-jabonpolvo-1",
      name: "Jabón en polvo",
      brandId: "b-ayudin",
      categoryId: "c-lavado",
      color: "oklch(0.78 0.09 265)",
      variants: [{ label: "800 gr", price: 3900 }],
      inStock: true,
    },
    {
      id: "p-malbec-1",
      name: "Malbec reserva",
      brandId: "b-trapiche",
      categoryId: "c-tintos",
      color: "oklch(0.38 0.13 20)",
      variants: [{ label: "750 ml", price: 7200 }],
      inStock: true,
    },
    {
      id: "p-cabernet-1",
      name: "Cabernet Sauvignon",
      brandId: "b-trapiche",
      categoryId: "c-tintos",
      color: "oklch(0.34 0.12 15)",
      variants: [{ label: "750 ml", price: 6800 }],
      inStock: true,
    },
    {
      id: "p-chardonnay-1",
      name: "Chardonnay",
      brandId: "b-trapiche",
      categoryId: "c-blancos",
      color: "oklch(0.86 0.09 105)",
      variants: [{ label: "750 ml", price: 6400 }],
      inStock: false,
    },
    {
      id: "p-leche-1",
      name: "Leche entera",
      brandId: "b-serenisima",
      categoryId: "c-leches",
      color: "oklch(0.93 0.02 250)",
      variants: [
        { label: "1 lt", price: 1400 },
        { label: "Pack x6", price: 7900 },
      ],
      inStock: true,
    },
    {
      id: "p-yogur-1",
      name: "Yogur bebible",
      brandId: "b-serenisima",
      categoryId: "c-yogures",
      color: "oklch(0.85 0.09 20)",
      variants: [{ label: "900 gr", price: 2500 }],
      inStock: true,
    },
    {
      id: "p-queso-1",
      name: "Queso cremoso",
      brandId: "b-serenisima",
      categoryId: "c-quesos",
      color: "oklch(0.9 0.07 95)",
      variants: [{ label: "500 gr", price: 5600 }],
      inStock: true,
    },
    {
      id: "p-asado-1",
      name: "Asado de tira",
      brandId: "b-molinos",
      categoryId: "c-vacuna",
      color: "oklch(0.5 0.15 22)",
      variants: [{ label: "1 kg", price: 9800 }],
      inStock: true,
    },
    {
      id: "p-pollo-1",
      name: "Pollo entero",
      brandId: "b-molinos",
      categoryId: "c-aves",
      color: "oklch(0.83 0.07 85)",
      variants: [{ label: "1 kg", price: 4200 }],
      inStock: true,
    },
    {
      id: "p-shampoo-1",
      name: "Shampoo nutritivo",
      brandId: "b-dove",
      categoryId: "c-cabello",
      color: "oklch(0.8 0.05 300)",
      variants: [{ label: "400 ml", price: 4700 }],
      inStock: true,
    },
    {
      id: "p-jabontocador-1",
      name: "Jabón de tocador",
      brandId: "b-dove",
      categoryId: "c-cuerpo",
      color: "oklch(0.88 0.04 330)",
      variants: [{ label: "90 gr", price: 1250 }],
      inStock: true,
    },
    {
      id: "p-alfajor-1",
      name: "Alfajor triple",
      brandId: "b-arcor",
      categoryId: "c-kiosco",
      color: "oklch(0.45 0.08 55)",
      variants: [{ label: "Unidad", price: 1100 }],
      inStock: true,
    },
  ],
};
